### PR TITLE
fix(textinput): make textinput.Model satisfy tea.Model interface

### PR DESCRIPTION
**Pull request by twpayne**
An early step towards #483.

### CODE REVIEW

**Comment by bashbunni** [comment]
Hey @twpayne! Heads up, we're figuring out a solution to this right now. When we try to make the bubbles implement the `tea.Model` interface, we end up having to do a lot of type assertions. For example, here's what it would look like to update a `viewport` bubble that implements `tea.Model`:
```go
// Pretend viewport.Model implements
// tea.Model here
type model {
    vp viewport.Model
}

// Some time later...
newModel, cmd := m.vp.Update(msg)
if newVPModel, ok := newModel(viewport.Model); ok {
    m.vp = newCVPModel
}
```
by comparison, this is the solution with the way to update the `viewport` model right now:
```go
m.vp, cmd := m.vp.Update(msg) // DONE
```

Just wanted to be transparent on this one as any activity on this PR is likely going to be on hold until these refactors are ironed out :)

**Comment by twpayne** [comment]
Ah, thanks for the info. I wanted to add this so I could easily add tests in a follow-up PR. I've been using [the following generic function](https://github.com/twpayne/chezmoi/blob/88b586dd4f6f9c61413631369f6a7195a6935c2f/internal/chezmoibubbles/chezmoibubbles_test.go#L37-L50) in my tests for [my small collection of bubbles](https://github.com/twpayne/chezmoi/tree/88b586dd4f6f9c61413631369f6a7195a6935c2f/internal/chezmoibubbles):

```go
func testRunModelWithInput[M tea.Model](t *testing.T, model M, input string) M {
	t.Helper()
	for _, msg := range makeKeyMsgs(input) {
		m, _ := model.Update(msg)
		var ok bool
		model, ok = m.(M)
		assert.True(t, ok)
	}
	return model
}
```

This allows me to write generic tests without type assertions, [like this](https://github.com/twpayne/chezmoi/blob/88b586dd4f6f9c61413631369f6a7195a6935c2f/internal/chezmoibubbles/boolinputmodel_test.go#L64-L68):

```go
		t.Run(tc.name, func(t *testing.T) {
			actualModel := testRunModelWithInput(t, NewBoolInputModel("prompt", tc.defaultValue), tc.input)
			assert.Equal(t, tc.expectedCanceled, actualModel.Canceled())
			assert.Equal(t, tc.expectedValue, actualModel.Value())
		})
```

I'm sure you've already considering this and similar approaches.

**Comment by meowgorithm** [comment]
Hey, @twpayne — just wanted to follow up on this one. This is something we're planning on addressing in Bubbles v2 because it changes the API pretty fundamentally.

Your examples here are a big part of why we're open to making this change, so thank you!

**Comment by twpayne** [comment]
Great, it sounds like this PR will be superseded, so I'll close it for now.

**Comment by meowgorithm** [comment]
Sounds good, Tom. I'll mention you in the proposal when we have it.

**Pull request closed without merging**
