### PR TITLE
Add tests for paginator

### PR DESCRIPTION
**Pull request by anirudhaCodes**
Added tests for paginator.

### CODE REVIEW

**Comment by maaslalani** [comment]
Thanks so much for theses test @anirudhaCodes, awesome work!

**Review by maaslalani — APPROVED** [review]

**Comment by anirudhaCodes** [comment]
I will increase the coverage.

**Comment by maaslalani** [comment]
Coverage check failing is not your fault, I fixed that over here: https://github.com/charmbracelet/bubbles/commit/3f2cd55237a0299c69da67cda21965238e9ae352

**Comment by anirudhaCodes** [comment]
> ge check failing is not your fault, I fixed that over here: [3f2cd55](https://github.com/charmbracelet/bubbles/commit/3f2cd55237a0299c69da67cda21965238e9ae352)

```
ok      github.com/charmbracelet/bubbles/paginator      0.237s  coverage: 65.0% of statements
```

I will try to improve the test coverage.

**Pull request merged**
