### PR TITLE
feat+fix: bracketed paste in textinput + textarea, avoid ctl chars in clipboard input

### PR DESCRIPTION
**Pull request by knz**
Completes the fix to https://github.com/charmbracelet/bubbletea/issues/404

https://github.com/charmbracelet/bubbletea/pull/397

Also, informs #263.

cc @muesli @maaslalani

### CODE REVIEW

**Comment by knz** [comment]
Need to wait until the other two PRs are merged before we can do CI on this one.

**Comment by knz** [comment]
@muesli this is ready too. I have removed the inter-dependency with the other PR so that the order of release does not matter any more.

**Comment by maaslalani** [comment]
Hey @knz! I have tested all of the examples in the Bubble Tea repo with this PR and everything looks great!

Thank you so much for this PR and contribution 🙇

**Comment by knz** [comment]
Thank you!

**Pull request merged**
