### PR TITLE
feat(textarea/textinput): support overwrite mode

### PR DESCRIPTION
**Pull request by knz**
For use with https://github.com/charmbracelet/bubbletea/pull/418.

cc @muesli @maaslalani

### CODE REVIEW

**Comment by muesli** [comment]
@knz Mind rebasing this for us?

**Comment by knz** [comment]
Done, but note that for this to build properly it needs a release of bubbletea that contains https://github.com/charmbracelet/bubbletea/pull/418

Otherwise, I'd need to update the textinput bubble to use key.Binding (which is what textarea does already). I know we've talked with @maaslalani about this but I don't have a PR for it yet.

**Comment by knz** [comment]
Alternatively I can rebase this on top of #270 so it does not need a go.mod update immediately. WDYT?

**Comment by knz** [comment]
Ok, done. This is now ready.

**Comment by knz** [comment]
@maaslalani anything else you'd like to happen here?

**Pull request closed without merging**
