### PR TITLE
feat: table widget

### PR DESCRIPTION
**Pull request by wesleimp**
## Improvements

This is the basic implementation of the table widget. Maybe some improvements for the next could be:

- Auto resize columns when has leftover width
- Optional static header
- Pagination

### CODE REVIEW

**Comment by maaslalani** [comment]
image

image

Did some customization and styling, I think it's looking good!

**Comment by meowgorithm** [comment]
LGTM. I think this one is ready to go!

**Comment by meowgorithm** [comment]
Actually, let me make one small edit to the keybindings so they better match pagers…

**Comment by meowgorithm** [comment]
Alright, done on my end. Squash ’n merge when you feel it's ready. Nice work on this one @wesleimp.

**Comment by maaslalani** [comment]
Fantastic work @wesleimp! Thank you so much for the contribution! 🎉 

This will be included in the next release.

**Pull request merged**
