### PR TITLE
Adds Simple Filepicker Bubble

### PR DESCRIPTION
**Pull request by taigrr**
Hello charm team! I reached out to you via slack and offered to add our filepicker bubble upstream, so here it is.

I'm sure there's work to be done for it to get accepted, and I know we will need to rebase before final merging can take place, but I wanted to start the conversation here and now and make any change requests before the final rebase to keep the rebasing chaos to a minimum.

Looking forward to getting this pulled upstream!

cc @bashbunni @squrki

### CODE REVIEW

**Comment by bashbunni** [comment]
Hey @taigrr any chance you could provide an example for using the file picker bubble that we can use to test the functionality?

**Comment by taigrr** [comment]
Yes! We already have an example app. Let me find it and make sure it's public.

**Comment by maaslalani** [comment]
Hey @taigrr, just as a heads up we are introducing a file picker bubble here which is being used in Gum / Soft Serve, let us know if you have any feedback / if it meets your needs:

* https://github.com/charmbracelet/bubbles/pull/343

**Comment by taigrr** [comment]
@squrki can you take a look at the differences in feature coverage here? I know we support dual-pane browsing, for example.

**Comment by squrki** [comment]
@maaslalani, this filepicker code activates in only the current directory, and it doesn't allow movement between parent and sub folders. My code allows for these. It also allows for single or dual panes to see the parent folder contents. Would you be interested in having this functionality added?

**Comment by maaslalani** [comment]
We do allow setting the `CurrentDirectory` now: https://github.com/charmbracelet/bubbles/commit/1ca90b3c942b5833c53a6fdfef78cd1fddfe6025

We also do allow movement between parent and subfolders! (do let me know if it's not working or if I'm misinterpreting the comment, you can try the bubble with `gum file`)

I can see the multiple panes being a good feature addition as well!

**Pull request closed without merging**
