### PR TITLE
feat(table): More granular table styles #246

### PR DESCRIPTION
**Pull request by pja237**
@jlec et al.
PR regarding #246 

This was an idea of how one might extend the table styling without causing too much havoc in the table code and to maintain backwards compatibility.
I'm more then happy to receive feedback, ideas and pointers on how to make this better and eventually merged.

### CODE REVIEW

**Comment by jlec** [comment]
This week is nuts. Hopefully, on the weekend, I will be able to tinker with your code

**Comment by jlec** [comment]
Works for me. docs are missing.

**Comment by bashbunni** [comment]
Part of me wonders if it would be more streamlined to extend the existing `Styles` struct to include an optional value for `Row`. It looks like there are already options for `Selected` and `Cell` in the `Styles` struct. The user would be able to set these styles to whatever `lipgloss.Style` definitions they'd like when they initialize the table. 

The `Row` field could probably just initialize a new style (`lipgloss.NewStyle()`), so all fields could call lipgloss.Render without issue and users can add their own customizations without it breaking. Let me know your thoughts on that

**Review by bashbunni — CHANGES_REQUESTED** [review]
Thank you so much for the PR! Looking forward to seeing the updates. It'll be great to be able to customize these tables further

**Comment by maaslalani** [comment]
Hey @pja237, thanks so much for this contribution.

Our plan is to replace the table renderer with Lip Gloss tables which will allow fully customizable Cell and Row styles with the `StyleFunc`.

I am going to close this PR for now (doing some cleaning up) but feel free to re-open this or create new issues / PRs if needed!

**Comment by maaslalani** [comment]
Here is the Lip Gloss table documentation for reference:

https://github.com/charmbracelet/lipgloss/tree/master?tab=readme-ov-file#rendering-tables

**Pull request closed without merging**
