### PR TITLE
Dual pane model

### PR DESCRIPTION
**Pull request by squrki**
Adds dualPane functionality as discussed. Please see demo below:

dualPane

cc: @maaslalani @taigrr @bashbunni

### CODE REVIEW

**Comment by taigrr** [comment]
Hmm, looks like the linter is acting up, it's complaining about a line of code that's no longer there ¯\\\_(ツ)_/¯

**Comment by taigrr** [comment]
@squrki can you rerun your tests with the merged-in funcs added by @meowgorithm ?

**Comment by squrki** [comment]
> @squrki can you rerun your tests with the merged-in funcs added by @meowgorithm ?

I confirm that it works the same as before.

**Comment by bashbunni** [comment]
Hey, thank you so much for this, and sorry for the delay! We're leaning towards not merging this due to the maintenance cost. It also adds rigidity in a case where it would likely be sufficient to provide guidance, yet allow the users to decide on the implementation themselves. We're a small team, so we have to be very careful about what abstractions we want to officially support.

If you wanted to make the bubble available to others, you can put it in your own repo and we would be happy to feature it in the [additional bubbles section](https://github.com/charmbracelet/bubbles?tab=readme-ov-file#additional-bubbles). Just create a PR with a link to your repo in that section of the README :)

**Pull request closed without merging**
