### PR TITLE
(fix)textInput: Placeholder View now respects set Width, Paste Fix

### PR DESCRIPTION
**Pull request by hopefulTex**
Pointed out by Discord user TooManyBison , the `placeholderView()` function would not add padding to match a given `Width`.
This was inconsistent with the standard `View()` function, which compares the text width with the content and adds padding accordingly.

This patch brings the width calculation from `View()` into the `placeholderView()` function, and additionally includes a minor fix when pasting text.

### CODE REVIEW

**Comment by donovanhubbard** [comment]
This looks like a duplicate of https://github.com/charmbracelet/bubbles/pull/442 which fixes this issue https://github.com/charmbracelet/bubbles/issues/358

**Comment by hopefulTex** [comment]
> This looks like a duplicate of #442 which fixes this issue #358

Oh noice, at the very least it increases chances of this getting fixed!

**Comment by maaslalani** [comment]
Hey, thank you for the PR, we merged #442!

**Comment by meowgorithm** [comment]
Thanks for the PR, Rose! Just closing this one to close the loop.

**Pull request closed without merging**
