### PR TITLE
Add calendar component

### PR DESCRIPTION
**Pull request by gfeun**

### CODE REVIEW

**Comment by maaslalani** [comment]
@gfeun This is absolutely awesome! I know it's been a while but do you still want more reviews on this? If not, I can probably pick up where you left off. I think it would be a useful addition to [`Gum`](https://github.com/charmbracelet/gum) for easy date picking.

**Comment by gfeun** [comment]
Hey @maaslalani,

Thanks for awaking this PR, its been so long !

I have some unpushed changes locally that allows displaying multiple months side by side
Let me clean this up tonight and i'll push that, happy to have a review after that :smiley: 

image

**Comment by maaslalani** [comment]
Oh sweet! Cool, just ping me when you need a review!

**Comment by gfeun** [comment]
Hi again :wave: 

I have pushed the multi months part and tried to add some more comments to explain the whole thing.
I recorded a demo to get a feel of how it looks / works: 
render1660860649057 

The demo runs the code available in the companion PR here: https://github.com/charmbracelet/bubbletea/pull/145/files

The code is not so straightforward due to padding, line returns etc. And i feel i may have missed opportunities to make it simpler in some places. 

I got no more time to work on this today but for reference, this line smells like it could be optimized by pre-allocating the array once instead of in each View call: https://github.com/charmbracelet/bubbles/pull/76/files#diff-2f6b59027d9f6ec18fb232ae4f569614c7aa43fc4806b5f8586bdf9cda0a296eR91

The calendar is also English centric atm, and i did not test a non-english one so there may be some trouble there too.

Another limitation is that it is currently only working with week start on Monday, which may not suit to everyone.

Finally i am not familiar with the other components, best practices, conventions around this projects so don´t hesitate to point me to examples.

**Comment by maaslalani** [comment]
Thanks so much @gfeun, appreciate all the work!

**Comment by skatkov** [comment]
@gfeun just wanted to say, that I love your work here and the fact that you took inspiration from `cal` utility. 

I know, that this is a work in progress, just wanted to cheap in saying that it would be awesome to have an ability to highlight or mark multiple days in that calendar. Once this will get merged, I might take a stab to implement that. Would be awesome if you consider this feature as future addition in your current implementation.

Thanks again.

**Comment by knz** [comment]
This is cool!

**Comment by bashbunni** [comment]
@meowgorithm are there any styling changes we would want to see before merging?

**Comment by meowgorithm** [comment]
Will be a little bit before we can properly review this, but thank you @bashbunni for bubbling this up.

**Comment by maaslalani** [comment]
Hey @gfeun! Thank you so much for the contribution again! ❤️

I think this is now a duplicate of:

* https://github.com/charmbracelet/bubbles/pull/475

I'm cleaning up some old PRs so I will close this PR in favour of #475 and hopefully we can get this DateTime / Calendar component in soon!

**Pull request closed without merging**
