### PR TITLE
chore: switch to x/ansi for text manipulation

### PR DESCRIPTION
**Pull request by aymanbagabas**
Need to be consistent with Lipgloss and https://github.com/charmbracelet/lipgloss/pull/279

### CODE REVIEW

**Comment by aymanbagabas** [comment]
P.S. @mikelorant I haven't tested any of the bubbles yet

**Comment by mikelorant** [comment]
Looks like we need to check:
- List
- Progress

**Comment by mikelorant** [comment]
@aymanbagabas Have confirmed that both `list` and `progress` are working correctly with the changes (based on modified examples that are part of Bubble Tea). Unit tests are also passing successfully.

I believe this is safe to merge.

**Review by mikelorant — APPROVED** [review]

**Review by caarlos0 — APPROVED** [review]

**Comment by mikelorant** [comment]
@meowgorithm @aymanbagabas Can we look at getting this one merged? This should mean we are free of the legacy string width functions in all the important places.

**Pull request merged**
