### PR TITLE
Implement Memoization to Speed Up Textarea Rendering

### PR DESCRIPTION
**Pull request by wesen**
This pull request introduces a significant performance improvement to the
textarea rendering process by implementing memoization to cache the results of
the wrapping computation. This change reduces the computational overhead
associated with repeated calculations, particularly for larger text areas.

This at least partially fixes https://github.com/charmbracelet/bubbletea/issues/831
although insertion and rewrapping are still "suboptimal". I think it does the job 
quite nicely in practice.

Key Changes:

1. **Introduction of `memoization.go`**: This new file contains the
   implementation of a generic memoization cache with a Least Recently Used
   (LRU) eviction policy. The cache is thread-safe and can be used with any type
   that implements the `Hasher` interface.

2. **Addition of `MemoCache` to `Model` struct**: The `Model` struct in
   `textarea.go` now includes a `MemoCache` instance for caching the results of
   the wrapping computation.

3. **Modification of `wrap` function calls**: All calls to the `wrap` function
   in `textarea.go` have been replaced with calls to the new `memoizedWrap`
   function. This function checks the cache for a precomputed result before
   falling back to the `wrap` function if necessary.

4. **Addition of `WrapInput` struct and `Hash` method**: The `WrapInput` struct
   and its associated `Hash` method have been added to facilitate the hashing of
   inputs to the wrapping computation for cache storage.
   
**Important**: I reused my generic Memoization which bumps go to 1.18. I'm not sure how consequent it is to introduce that kind of change incidentally, but didn't want to remove the generics for now. I can "instantiate" it all to string if sticking with 1.17 is desired.

**Disclaimer**: I'm pretty bullish on LLMs for programming. The memoization code, the fuzzer and the unit tests are heavily copiloted and GPT4-ed. I haven't tested the concurrency of the data structure explicitly, I'm happy to add a bunch of tests and fuzzers for that as well.

### CODE REVIEW

**Comment by nadimkobeissi** [comment]
Please merge this!

**Comment by wesen** [comment]
> Please merge this!

You can try to use https://github.com/go-go-golems/bobatea which is my alternative version, until it's merged. I haven't tried it out outside of my go workspace, so I hope it works for you.

**Comment by maaslalani** [comment]
Hi! Thank so much for this PR, I am going to test this out very soon so we can get this in! We really appreciate the work on this one.

**Comment by maaslalani** [comment]
Really solid work @wesen. Thank you so much for these improvements! I noticed a tonne of improved performance with this.

One thing I did change (when testing with 1000 lines of text) it was still slow until I changed the cache capacity to match the number of lines. Instead of hardcoding this, I make it so that the capacity matches the `MaxHeight` of the `textarea` so we can support the performance at large MaxHeights as well.

**Pull request merged**
