### PR TITLE
Add selection prompt

### PR DESCRIPTION
**Pull request by erikgeiser**
This PR adds a selection prompt with the following features:
* Optional Pagination
* Optional Filtering
* Customizable appearance (with color/style support via https://github.com/muesli/termenv)
* Custom choice types
* Proper wrapping for small terminals via https://github.com/muesli/reflow

Examples:
[asciicast](https://asciinema.org/a/4ZK5HZ2uJm8NtC0rs8rnqxUwS)
[asciicast](https://asciinema.org/a/HZ7BOXUgOsFx7u5p1eId9I33b)

### CODE REVIEW

**Comment by meowgorithm** [comment]
Thanks for the PR! At first glance this looks pretty good. Could you add an example application in a subdirectory (perhaps called `example`)?

**Comment by meowgorithm** [comment]
Actually, never mind; found your PromptKit project 😄

**Comment by erikgeiser** [comment]
My bad, I forgot to add the asciinema recordings I made for #25.

There's one concern I have before merging. This prompt supports custom key mappings, and a default key map is used when instantiating it via `NewModel()`. However, if a user manually instantiates it (`m := selection.Model{}`) it will not react to user input at all when no key map is set and the program has to be killed. Is that a user error or should I add some logic to detect whether the bare minimum set of keys is defined in the key map (maybe up, down, select). If not it would throw an error on startup.

Now, when writing this down, I think I should definitely do this.

**Comment by erikgeiser** [comment]
Another consideration: Should I change the `NewModel` signature to take the choices as an argument? Currently, I chose the `NewModel` signature without arguments to be in line with the other models in this package. However, given that the choices are obviously mandatory it would make sense to take it as an argument such that `NewModel` returns a working prompt.

**Comment by meowgorithm** [comment]
Yes, that makes sense; so maybe something like `func NewModel(choices ...[]string)` to keep it light. Another option might be to use functional arguments to allow for different ways of constructing the choices:

```go
m := NewModel(WithChoices("a", b"))
```

This would also allow other options such as:

```go
m := NewModel(
    WithChoices(c),
    WithKeybindings(k),
)
```

**Comment by erikgeiser** [comment]
I would have used `NewModel(choices []*Choices)`. This would then be used like this: `NewModel(SliceChoices(mySlice))`. This would cover all use cases and not just strings. In my opinion this is important because often the choices are arbitrary objects like in the custom example (see also second video above):

```go
choices := []Article{
    {ID: "123", Name: "Article A"},
    {ID: "234", Name: "Article B"},
    {ID: "345", Name: "Article C"},
    {ID: "456", Name: "Article D"},
    {ID: "567", Name: "Article E"},
}

prompt := selection.NewModel(selection.SliceChoices(choices))
prompt.Label = "Choose an article!"
prompt.PageSize = 3
prompt.Template = customTemplate
prompt.Filter = func(filter string, choice *selection.Choice) bool {
    article, _ := choice.Value.(Article)

    return strings.Contains(article.ID, filter)
}

```

I think that your second option would be too much given that the user can just set the optional configuration directly on the model. This also feels more in line with the other models. The choices would be taken as an argument only because they are mandatory.

**Comment by erikgeiser** [comment]
Is there anything I can do or change to move forward with this?

**Comment by meowgorithm** [comment]
@erikgeiser Sorry for the delay on this one; we've been really busy over here. It may be a little while until we can give this a proper review, but we will get to it.

**Comment by erikgeiser** [comment]
Do you still plan to do something about this PR?

**Comment by meowgorithm** [comment]
Hey Erik. We looked at this again, and while the component is a bit too specific for this repository, we really like it. Would you be open to creating a repository for it so we can link to it from the README as an additional resource?

**Comment by erikgeiser** [comment]
Okay, I can work with that decision. I'll see if I can find the time to make a small prompt library around the selection prompt.

**Comment by meowgorithm** [comment]
Sounds good. Please do let us know when it's ready.

I enjoyed reading your code, by the way. They notion of a key map you came up with was particularly impressive.

**Comment by erikgeiser** [comment]
Thank you.

Ultimately, I think it is a good decision not to merge this into `bubbles`. Looking back I developed it to be directly used as a prompt by users while most other `bubbles` components are more like widgets that are intended to be used in larger models.

I took this opportunity to create a prompt library on top of `bubbles` containing this selection prompt:

https://github.com/erikgeiser/promptkit

**Comment by meowgorithm** [comment]
It's great to see another release of promptkit and nice that the library works both standalone and as something that can be integrated into a larger Bubble Tea project.

I've added promptkit to the [README](https://github.com/charmbracelet/bubbles#additional-bubbles).

**Comment by erikgeiser** [comment]
Thank you, currently the library is fairly limited due to https://github.com/charmbracelet/bubbletea/issues/24 as you can only run one prompt before key strokes are lost, but I'll see what I can due about that issue.

**Comment by meowgorithm** [comment]
Ah, good point. It's an interesting issue and a tricky one to solve from what I understand. There are some notes in the thread around it: you're more than welcome to take a look.

**Comment by muesli** [comment]
Gonna close this one, as we resolved the situation. Thank you for all your amazing work, @erikgeiser!

**Pull request closed without merging**
