### PR TITLE
fix(textinput): slicing outside cap

### PR DESCRIPTION
**Pull request by MikaelFangel**
Fixes: #531
Fixes: https://github.com/charmbracelet/gum/issues/591

### Changes
 - Manually assigned `p` with the size of the `Width + 1` because when you use `var()` to assign, the cap defaults to 32 and thus it is possible to get out of bounds errors.

### CODE REVIEW

**Review by caarlos0 — APPROVED** [review]
thanks! can you add a test for it?

**Comment by MikaelFangel** [comment]
I appreciate your patience with this.
I've added a test that makes slicing outside cap occur when the fix is not applied. (:

**Comment by MikaelFangel** [comment]
Sure, I've added a test now that fails without the fix applied.

**Comment by MikaelFangel** [comment]
@caarlos0 - Do I need to do anything else before it can be merged? 😄

**Comment by bashbunni** [comment]
@MikaelFangel thank you so much for identifying this and fixing it!

**Pull request merged**
