### PR TITLE
feat: Allow to mark colums as hidden. This might be helpful to hide s…

### PR DESCRIPTION
**Pull request by deicon**
Tables might contain more than needs to be visible to the user. 
Consider a table like 

ID  PrimaryKey          UserName
1    12392839281.    My_Username

Once displayed to the user, we want the user to select a row but don't want to expose the PrimaryKey. This is only used after
user selection for further processing. 

This can then be used to enable https://github.com/charmbracelet/gum/issues/320

### CODE REVIEW

**Comment by deicon** [comment]
@maaslalani any chance this gets a review any time soon ?

**Comment by maaslalani** [comment]
> @maaslalani any chance this gets a review any time soon ? 
> 
> 

Hey @deicon, because of the new Lip Gloss tables (https://github.com/charmbracelet/lipgloss/releases/tag/v0.9.0) we're currently integrating that renderer into Bubbles which will then be used in Gum. So we should review / revisit this feature after the new table renderer is introduced in Bubbles and Gum.

**Comment by maaslalani** [comment]
Hey @deicon, we recently introduced hiding a column by setting the width to 0:

* https://github.com/charmbracelet/bubbles/pull/465

Let us know if this solves your use case, feel free to re-open this PR or create a new issue if it doesn't!

**Comment by deicon** [comment]
@maaslalani Kind of. Mostly I was trying to fix https://github.com/charmbracelet/gum/issues/320
by a PR in GUM. to make this even better, I would love to hide some columns but still use values of columns as return values from the gum table command. https://github.com/charmbracelet/gum/pull/415

**Pull request closed without merging**
